"""
IsaacGym vs MuJoCo sim2sim alignment helpers.

Reference rollout is expected to be generated by:
`wheel_legged_gym/scripts/collect_isaac_reference_rollout.py`
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Tuple

import numpy as np

from .mujoco_balance_env import MuJoCoBalanceEnv


OBS_GROUPS = {
    "ang_vel": slice(0, 3),
    "gravity": slice(3, 6),
    "commands": slice(6, 9),
    "theta0": slice(9, 11),
    "theta0_dot": slice(11, 13),
    "L0": slice(13, 15),
    "L0_dot": slice(15, 17),
    "wheel_pos": slice(17, 19),
    "wheel_vel": slice(19, 21),
    "last_actions": slice(21, 27),
}


def _rmse(a: np.ndarray, b: np.ndarray) -> float:
    if a.size == 0 or b.size == 0:
        return float("nan")
    return float(np.sqrt(np.mean((a - b) ** 2)))


def load_reference_rollout(path: str | Path) -> Dict[str, Any]:
    path = Path(path)
    with np.load(path, allow_pickle=True) as data:
        out: Dict[str, Any] = {}
        for key in data.files:
            out[key] = data[key]
    if "metadata_json" in out:
        meta_raw = out["metadata_json"]
        if isinstance(meta_raw, np.ndarray):
            meta_raw = meta_raw.item()
        out["metadata"] = json.loads(meta_raw)
    return out


def _contact_match_rate(ref_contacts: np.ndarray, mj_contacts: np.ndarray) -> Dict[str, float]:
    if ref_contacts.shape != mj_contacts.shape or ref_contacts.size == 0:
        return {
            "overall": float("nan"),
            "base_contact": float("nan"),
            "left_wheel_contact": float("nan"),
            "right_wheel_contact": float("nan"),
        }
    match = ref_contacts == mj_contacts
    return {
        "overall": float(np.mean(match)),
        "base_contact": float(np.mean(match[:, 0])),
        "left_wheel_contact": float(np.mean(match[:, 1])),
        "right_wheel_contact": float(np.mean(match[:, 2])),
    }


def replay_reference_rollout_in_mujoco(
    reference_rollout_path: str | Path,
    model_path: str | Path,
    controller_mode: str = "vmc_balance_exact",
    domain_rand_mode: str = "off",
    mujoco_tuning_profile: str = "exact_baseline",
    seed: int = 0,
    max_steps: int | None = None,
) -> Dict[str, Any]:
    ref = load_reference_rollout(reference_rollout_path)

    actions = np.asarray(ref["actions"], dtype=np.float64)
    T = int(actions.shape[0])
    if max_steps is not None:
        T = min(T, int(max_steps))
        actions = actions[:T]

    env = MuJoCoBalanceEnv(
        str(model_path),
        render=False,
        seed=seed,
        controller_mode=controller_mode,
        domain_rand_mode=domain_rand_mode,
        mujoco_tuning_profile=mujoco_tuning_profile,
    )

    # Reference init state (Isaac root quaternion is xyzw)
    root_state = np.asarray(ref["init_root_state"], dtype=np.float64)
    init_dof_pos = np.asarray(ref["init_dof_pos"], dtype=np.float64)
    init_dof_vel = np.asarray(ref["init_dof_vel"], dtype=np.float64)
    env.reset(randomize=False, domain_randomize=False)
    env.set_state(
        root_pos=root_state[0:3],
        root_quat_xyzw=root_state[3:7],
        root_lin_vel=root_state[7:10],
        root_ang_vel=root_state[10:13],
        dof_pos=init_dof_pos,
        dof_vel=init_dof_vel,
        reset_buffers=True,
    )

    # Replay and collect MuJoCo trajectory
    mj_obs = []
    mj_torques = []
    mj_root_pos = []
    mj_root_quat_xyzw = []
    mj_root_lin_vel = []
    mj_root_ang_vel = []
    mj_dof_pos = []
    mj_dof_vel = []
    mj_projected_gravity = []
    mj_L0 = []
    mj_theta0 = []
    mj_contacts = []
    mj_control_debug = []

    for t in range(T):
        obs, rew, done, info = env.step(actions[t])
        snap = env.get_state_snapshot()
        debug = env.get_debug_state()
        contacts = env.get_contact_flags()

        mj_obs.append(np.asarray(obs, dtype=np.float64))
        mj_torques.append(np.asarray(env.last_ctrl, dtype=np.float64))
        mj_root_pos.append(np.asarray(snap["root_pos"], dtype=np.float64))
        mj_root_quat_xyzw.append(np.asarray(snap["root_quat_xyzw"], dtype=np.float64))
        mj_root_lin_vel.append(np.asarray(snap["root_lin_vel"], dtype=np.float64))
        mj_root_ang_vel.append(np.asarray(snap["root_ang_vel"], dtype=np.float64))
        mj_dof_pos.append(np.asarray(snap["dof_pos"], dtype=np.float64))
        mj_dof_vel.append(np.asarray(snap["dof_vel"], dtype=np.float64))
        mj_projected_gravity.append(np.asarray(snap["projected_gravity"], dtype=np.float64))
        mj_L0.append(np.asarray(snap["L0"], dtype=np.float64))
        mj_theta0.append(np.asarray(snap["theta0"], dtype=np.float64))
        mj_contacts.append(
            np.array(
                [
                    contacts["base_contact"],
                    contacts["left_wheel_contact"],
                    contacts["right_wheel_contact"],
                ],
                dtype=np.bool_,
            )
        )
        mj_control_debug.append(debug.get("control_debug", {}))

    env.close()

    mj_obs = np.asarray(mj_obs, dtype=np.float64)
    mj_torques = np.asarray(mj_torques, dtype=np.float64)
    mj_root_pos = np.asarray(mj_root_pos, dtype=np.float64)
    mj_root_quat_xyzw = np.asarray(mj_root_quat_xyzw, dtype=np.float64)
    mj_root_lin_vel = np.asarray(mj_root_lin_vel, dtype=np.float64)
    mj_root_ang_vel = np.asarray(mj_root_ang_vel, dtype=np.float64)
    mj_dof_pos = np.asarray(mj_dof_pos, dtype=np.float64)
    mj_dof_vel = np.asarray(mj_dof_vel, dtype=np.float64)
    mj_projected_gravity = np.asarray(mj_projected_gravity, dtype=np.float64)
    mj_L0 = np.asarray(mj_L0, dtype=np.float64)
    mj_theta0 = np.asarray(mj_theta0, dtype=np.float64)
    mj_contacts = np.asarray(mj_contacts, dtype=np.bool_)
    # Extract MuJoCo control intermediates (if controller debug is available)
    def _stack_debug_array(key: str, width: int) -> np.ndarray:
        rows = []
        for item in mj_control_debug:
            val = item.get(key)
            if val is None:
                rows.append(np.full((width,), np.nan, dtype=np.float64))
            else:
                arr = np.asarray(val, dtype=np.float64).reshape(-1)
                if arr.shape[0] != width:
                    rows.append(np.full((width,), np.nan, dtype=np.float64))
                else:
                    rows.append(arr)
        return np.asarray(rows, dtype=np.float64)

    mj_theta0_ref = _stack_debug_array("theta0_ref", 2)
    mj_l0_ref = _stack_debug_array("l0_ref", 2)
    mj_force_leg = _stack_debug_array("force_leg", 2)
    mj_torque_leg = _stack_debug_array("torque_leg", 2)

    # Reference arrays (optional per field; collector should emit them)
    ref_obs = np.asarray(ref.get("obs", np.empty((0, 27))), dtype=np.float64)[:T]
    ref_torques = np.asarray(ref.get("torques", np.empty((0, 6))), dtype=np.float64)[:T]
    ref_root_pos = np.asarray(ref.get("root_pos", np.empty((0, 3))), dtype=np.float64)[:T]
    ref_root_quat_xyzw = np.asarray(ref.get("root_quat_xyzw", np.empty((0, 4))), dtype=np.float64)[:T]
    ref_root_lin_vel = np.asarray(ref.get("root_lin_vel", np.empty((0, 3))), dtype=np.float64)[:T]
    ref_root_ang_vel = np.asarray(ref.get("root_ang_vel", np.empty((0, 3))), dtype=np.float64)[:T]
    ref_dof_pos = np.asarray(ref.get("dof_pos", np.empty((0, 6))), dtype=np.float64)[:T]
    ref_dof_vel = np.asarray(ref.get("dof_vel", np.empty((0, 6))), dtype=np.float64)[:T]
    ref_projected_gravity = np.asarray(ref.get("projected_gravity", np.empty((0, 3))), dtype=np.float64)[:T]
    ref_L0 = np.asarray(ref.get("L0", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_theta0 = np.asarray(ref.get("theta0", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_theta0_ref = np.asarray(ref.get("theta0_ref", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_l0_ref = np.asarray(ref.get("l0_ref", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_force_leg = np.asarray(ref.get("force_leg", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_torque_leg = np.asarray(ref.get("torque_leg", np.empty((0, 2))), dtype=np.float64)[:T]
    ref_contacts = np.asarray(ref.get("contacts", np.empty((0, 3), dtype=np.bool_)))[:T]

    grouped_obs_rmse = {}
    if ref_obs.shape == mj_obs.shape and ref_obs.size > 0:
        for name, sl in OBS_GROUPS.items():
            grouped_obs_rmse[name] = _rmse(ref_obs[:, sl], mj_obs[:, sl])
        obs_rmse_total = _rmse(ref_obs, mj_obs)
    else:
        obs_rmse_total = float("nan")
        grouped_obs_rmse = {k: float("nan") for k in OBS_GROUPS}

    torque_rmse_total = _rmse(ref_torques, mj_torques) if ref_torques.shape == mj_torques.shape else float("nan")
    torque_rmse_per_joint = (
        [float(_rmse(ref_torques[:, i], mj_torques[:, i])) for i in range(6)]
        if ref_torques.shape == mj_torques.shape and ref_torques.size > 0
        else [float("nan")] * 6
    )

    state_rmse = {
        "base_height": _rmse(ref_root_pos[:, 2], mj_root_pos[:, 2]) if ref_root_pos.shape == mj_root_pos.shape else float("nan"),
        "base_pos": _rmse(ref_root_pos, mj_root_pos) if ref_root_pos.shape == mj_root_pos.shape else float("nan"),
        "base_quat_xyzw": _rmse(ref_root_quat_xyzw, mj_root_quat_xyzw)
        if ref_root_quat_xyzw.shape == mj_root_quat_xyzw.shape
        else float("nan"),
        "base_lin_vel": _rmse(ref_root_lin_vel, mj_root_lin_vel)
        if ref_root_lin_vel.shape == mj_root_lin_vel.shape
        else float("nan"),
        "base_ang_vel": _rmse(ref_root_ang_vel, mj_root_ang_vel)
        if ref_root_ang_vel.shape == mj_root_ang_vel.shape
        else float("nan"),
        "dof_pos": _rmse(ref_dof_pos, mj_dof_pos) if ref_dof_pos.shape == mj_dof_pos.shape else float("nan"),
        "dof_vel": _rmse(ref_dof_vel, mj_dof_vel) if ref_dof_vel.shape == mj_dof_vel.shape else float("nan"),
        "projected_gravity": _rmse(ref_projected_gravity, mj_projected_gravity)
        if ref_projected_gravity.shape == mj_projected_gravity.shape
        else float("nan"),
        "L0": _rmse(ref_L0, mj_L0) if ref_L0.shape == mj_L0.shape else float("nan"),
        "theta0": _rmse(ref_theta0, mj_theta0) if ref_theta0.shape == mj_theta0.shape else float("nan"),
    }

    vmc_intermediate_rmse = {
        "theta0_ref": _rmse(ref_theta0_ref, mj_theta0_ref)
        if ref_theta0_ref.shape == mj_theta0_ref.shape
        else float("nan"),
        "l0_ref": _rmse(ref_l0_ref, mj_l0_ref)
        if ref_l0_ref.shape == mj_l0_ref.shape
        else float("nan"),
        "force_leg": _rmse(ref_force_leg, mj_force_leg)
        if ref_force_leg.shape == mj_force_leg.shape
        else float("nan"),
        "torque_leg": _rmse(ref_torque_leg, mj_torque_leg)
        if ref_torque_leg.shape == mj_torque_leg.shape
        else float("nan"),
    }

    alignment = {
        "metadata": {
            "reference_rollout_path": str(Path(reference_rollout_path).resolve()),
            "model_path": str(Path(model_path).resolve()),
            "controller_mode": controller_mode,
            "domain_rand_mode": domain_rand_mode,
            "seed": int(seed),
            "num_steps_replayed": int(T),
        },
        "summary": {
            "obs_rmse_total": obs_rmse_total,
            "torque_rmse_total": torque_rmse_total,
        },
        "obs_group_rmse": grouped_obs_rmse,
        "torque_rmse_per_joint": torque_rmse_per_joint,
        "state_rmse": state_rmse,
        "vmc_intermediate_rmse": vmc_intermediate_rmse,
        "contact_alignment": _contact_match_rate(ref_contacts, mj_contacts)
        if ref_contacts.shape == mj_contacts.shape and ref_contacts.size > 0
        else {
            "overall": float("nan"),
            "base_contact": float("nan"),
            "left_wheel_contact": float("nan"),
            "right_wheel_contact": float("nan"),
        },
        "series_summary": {
            "final_base_height_mujoco": float(mj_root_pos[-1, 2]) if len(mj_root_pos) else None,
            "final_base_height_reference": float(ref_root_pos[-1, 2])
            if ref_root_pos.shape == mj_root_pos.shape and len(ref_root_pos)
            else None,
        },
    }
    return alignment
